### ISSUE TITLE
can't use portex after compilation

### ISSUE THREAD

**Issue by dummys** [katjahahn/PortEx#4]
Hi,

After sbt package

> $ java -jar portex_2.10-1.0.1.jar
no main manifest attribute, in portex_2.10-1.0.1.jar

**Comment by AnimeshShaw** [comment]
Thats because its th main library which you can import into your project or add to classpath. If you are looking for automatic report generation or CLI tool then download and use the PortExAnalyzer.jar from _here_ : - https://github.com/katjahahn/PortEx/tree/master/progs 

__DIrect download__ :- https://github.com/katjahahn/PortEx/blob/master/progs/PortexAnalyzer.jar?raw=true

When you use this on a sample.exe file you see something like as follows

    java -jar PortexAnalyzer.jar -o PortEx-Report-Sample.txt sample.exe
    PortEx Analyzer

    Creating report file...
    Writing header reports... 
    Writing section reports...
    Writing analysis reports...
    Done!`

**Comment by katjahahn** [comment]
To compile a fat jar that is useable via command line (PortexAnalyzer tool), type
    
    sbt assembly

The package command just makes a slim jar without a main entry. It is only used to be integrated as library.

I will add this to the readme to avoid confusion.

Thanks for the report!
